Repository lensapp/lens-platform-sdk, pull requests merged in 2021-06, with the labels that each got.

#37 Experiment with possible strategies for exception handling
  .env.example
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  .gitignore
  .vscode/launch.json
  integration-test/README.md
  integration-test/SpaceService.test.ts
  integration-test/UserService.test.ts
  integration-test/configuration.ts
  integration-test/integration-test.json
  integration-test/setup.ts
  integration-test/utils.ts
  package-lock.json
  package.json
  src/Exceptions.test.ts
  src/InvitationService.ts
  src/LensPlatformClient.test.ts
  src/LensPlatformClient.ts
  src/SpaceService.ts
  src/UserService.ts
  src/exceptions/HTTPErrrorCodes.ts
  src/exceptions/common.exceptions.ts
  src/exceptions/index.ts
  src/exceptions/invitation.exceptions.ts
  src/exceptions/space.exceptions.ts
  src/exceptions/user.exceptions.ts
  src/exceptions/utils.ts
  src/index.ts
  tsconfig.json
Labels: major

#73 Export type
  tsconfig.cjs.json
  tsconfig.esm.json
Labels: bug

#84 Add browser support
  README.md
  integration-test/SpaceService.test.ts
  package-lock.json
  package.json
  src/InvitationService.ts
  src/LensPlatformClient.test.ts
  src/LensPlatformClient.ts
  src/OpenIdConnect.ts
  src/PlanService.ts
  src/SpaceService.ts
  src/TeamService.ts
  src/UserService.ts
  src/exceptions/utils.ts
Labels: major

#96 Add error handling for removing user from Team
  integration-test/TeamService.test.ts
  src/TeamService.ts
  src/exceptions/index.ts
  src/exceptions/space.exceptions.ts
  src/exceptions/team.exceptions.ts
Labels: minor
